### ISSUE TITLE
Can not find Squirrel

### ISSUE THREAD

**Issue by natanielkd** [megahertz/electron-simple-updater#16]
Hi, 
Can you help me about squirrel.windows? I can't find how install it on my electron project.

Thanks in advance.

**Comment by megahertz** [comment]
If you use electron-builder you need to specify a build target in the package.json:
```js
"build": {
 ...
  "win": {
    "target": "squirrel"
  },
  ...
},
```

**Comment by natanielkd** [comment]
Hi, 
Thank you for your help, but the issue remains. Is there anything else to config about squirrel?

**Comment by megahertz** [comment]
Maybe you need to install an additional package https://github.com/electron-userland/electron-builder/wiki/Options#SquirrelWindowsOptions

**Comment by natanielkd** [comment]
Thank you!

**Comment by hieund-hblab** [comment]
@megahertz 
I got this issue on my project.
Could you help me?
Thanks!

**Comment by megahertz** [comment]
@hieund-hblab Did you install electron-builder-squirrel-windows?

**Comment by hieund-hblab** [comment]
@megahertz thanks for your reply, I used "electron-builder-squirrel-windows"
and below config to package.json file:
`
"win": {
      "target": "squirrel"
    },
    "squirrelWindows": {
      "msi": true,
      "target": "nsis"
    }
`
=> this issue "Can not find Squirrel" was pass, but I got new below issue, 
my server config for win is:
`"win32-x64-prod": {
    "readme": "Second release",
    "update": "http://example.local/ElectronApp-1.0.1.exe",
    "install": "http://example.local/ElectronApp-1.0.1.exe",
    "version": "1.0.1"
  },`

`
[2017-05-19 02:37:55:0345] [error] error Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__7.MoveNext()<---


    at AutoUpdater.emitError (C:\Users\Dell\AppData\Local\CubismHome\app-1.0.0\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:58:24)
    at squirrelUpdate.download (C:\Users\Dell\AppData\Local\CubismHome\app-1.0.0\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:34:21)
    at C:\Users\Dell\AppData\Local\CubismHome\app-1.0.0\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:89:14
    at ChildProcess.<anonymous> (C:\Users\Dell\AppData\Local\CubismHome\app-1.0.0\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:71:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
`

I tried to research but no solution for now, could you help me to check it?
Thanks so much!

**Comment by megahertz** [comment]
@hieund-hblab 
1. You need to use the same config for squirrel as in the example https://github.com/megahertz/electron-simple-updater/blob/master/example/package.json
2. Your update section points to exe, not to a squirrel update archive

**Comment by hieund-hblab** [comment]
@megahertz I got it, thanks for your support (y)

**Comment by DoggeHill** [comment]
Hi, I've got also a problem with the squirrel. Error: Can not find Squirrel. It is installed, my json is the same as yours and it does not work.

**Comment by megahertz** [comment]
@DoggeHill Hi. Have you read [this thread](https://github.com/electron/electron/issues/4535)?
