### ISSUE TITLE
Option to save the update downloaded

### ISSUE THREAD

**Issue by debelop13** [megahertz/electron-simple-updater#33]
Hi!

Once update is downloaded (autoDownload), I ask to the user if he want to update now, or remind later, if you click remind later, and you restart app, when is initializing, is downloading again the update..

Can I have the update downloaded yet and ask to update now directly when app is initializing?

Thanks!

**Comment by megahertz** [comment]
Unfortunately, Squirrel downloads updates by itself, so I can't control it.

**Comment by debelop13** [comment]
Hi, I want to download automatically but update only if user wants, in mac I can cancel, but in windows I can't.

I am using squirrel events to stop..

updater.on('squirrel-win-installer', onSquirrelInstalling);
function onSquirrelInstalling(event) {
      console.log(event)
}

But never is called.

My squirrel log 

2017-07-26 11:01:41> CheckForUpdateImpl: Downloading RELEASES file from http://www.example.com/example/standalone/releases/win32/0.0.8
2017-07-26 11:01:41> FileDownloader: Downloading url: http://www.example.com/example/standalone/releases/win32/0.0.8/RELEASES?id=example&localVersion=0.0.7&arch=amd64
2017-07-26 11:01:42> FileDownloader: Downloading file: http://www.example.com/example/standalone/releases/win32/0.0.8/example-0.0.8-full.nupkg
2017-07-26 11:02:56> ApplyReleasesImpl: Writing files to app directory: C:\Users\example\AppData\Local\example\app-0.0.8
2017-07-26 11:03:02> LogHost: Rigging execution stub for example_ExecutionStub.exe to C:\Users\example\AppData\Local\example\example.exe
2017-07-26 11:03:08> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\example\AppData\Local\example\app-0.0.8\example.exe]
2017-07-26 11:03:09> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-07-26 11:03:09> ApplyReleasesImpl: Examining Pin: Command Prompt.lnk
2017-07-26 11:03:09> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-07-26 11:03:09> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-07-26 11:03:09> ApplyReleasesImpl: Examining Pin: SourceTree.lnk
2017-07-26 11:03:09> ApplyReleasesImpl: Examining Pin: Task Manager.lnk
2017-07-26 11:03:09> ApplyReleasesImpl: Examining Pin: Visual Studio Code.lnk
2017-07-26 11:03:09> ApplyReleasesImpl: Fixing up tray icons
2017-07-26 11:03:09> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-07-26 11:03:09> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-07-26 11:03:09> ApplyReleasesImpl: cleanDeadVersions: for version 0.0.8
2017-07-26 11:03:09> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.0.7
2017-07-26 11:03:09> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.0.8

Thanks

**Comment by megahertz** [comment]
Hi. Sometimes squirrel updates the app even if quitAndInstall isn't called. I don't remember what's the exact squirrel behavior on different platforms.

As for squirrel-win-installer, you should subscribe to the event before updater.init is called.

**Comment by debelop13** [comment]
Is updating anyway, calling quitAndInstall or not.

I am in renderer.js, like your example, 
```

function attachUpdaterHandlers() {
  updater.on('update-available', onUpdateAvailable);
  updater.on('update-downloading', onUpdateDownloading);
  updater.on('update-downloaded', onUpdateDownloaded);
  updater.on('squirrel-win-installer', onSquirrelInstalling);
  updater.setOptions('logger', {
    info(text) {
      console.log("Information in Auto-update: " + String(text));
    },
    warn(text) {
      console.log("Warning in auto-update: " + String(text));
    }
  });

  function onUpdateAvailable(meta) {
    //If you want, ask for update
    /*if (window.confirm('Update ' + meta.version + ' is available. The current version is ' + updater.version + '. Do you like to download in background it now?', 'Update')) {
      updater.downloadUpdate();
    }*/
  }

  function onUpdateDownloading(meta) {
    console.log("The update is downloading...");
  }

  function onUpdateDownloaded(meta) {
    var index = dialog.showMessageBox(mainWindow, {
      type: 'info',
      buttons: ['Restart to update', 'Remind me later'],
      defaultId: 0,
      title: "Example",
      message: 'New version has been downloaded. Please restart the application to apply the updates.',
      detail: meta.readme,
      cancelId: 1
    });
    if (index === 1) {
      console.log("Aborting the update...")
      return;
    } else {
      // Restart app, then update will be applied
      updater.quitAndInstall();
    }
  }

  function onSquirrelInstalling(event) {
      event.preventDefault = true;
      console.log(event)
      console.log(event.squirrelAction)
  }
```

But is never calling..

Also try in main.js, before updater.init called.. 

```
updater.on('squirrel-win-installer', onSquirrelInstalling);
updater.init({
  checkUpdateOnStart: false,
  autoDownload: false
});

  function onSquirrelInstalling(event) {
      event.preventDefault = true;
      console.log(event)
      console.log(event.squirrelAction)
  }
```

And is only calling event in installation.. (event squirrel-install) not more..

I need to stop the update!

**Comment by megahertz** [comment]
Sorry that I misled you. I forgot some details about Squirrel.Win. 'squirrel-win-installer' is fired when the app has been updated.

I'm feeling bad now, so I can't give you a good solution. I'll try to return to this problem on the next week.

**Comment by debelop13** [comment]
Okey, no problem! I will be waiting

**Comment by megahertz** [comment]
I looked up at squirrel logic again. Normally, it updates the app as soon as updates are downloaded, so it doesn't matter whether the app restarted or not. How do you cancel the update on mac? 

If an app is updated but it still can find a new version after restart - in most situation it has wrong version configuration. Check whether the version property inside C:\Users\example\AppData\Local\example\app-0.0.8\resources\app.asar\package.json is correct.

**Comment by debelop13** [comment]
In mac, if I don't call 'updater.quitAndInstall()'.. is not updating

```
function onUpdateDownloaded(meta) {
    var index = dialog.showMessageBox(mainWindow, {
      type: 'info',
      buttons: ['Restart to update', 'Remind me later'],
      defaultId: 0,
      title: "Example",
      message: 'New version has been downloaded. Please restart the application to apply the updates.',
      detail: meta.readme,
      cancelId: 1
    });
    if (index === 1) {
      console.log("Aborting the update...")
      return;
    } else {
      // Restart app, then update will be applied
      updater.quitAndInstall();
    }
  }
```

In windows I see that before to onUpdateDownloaded callback, is created new app-0.0.8 (and saves app-0.0.7) and also application.exe has new version (0.0.8).. and after restar is updating anyway.. I thought that we could stop update.. or we could go back when users choose to not update

**Comment by megahertz** [comment]
It seems that Squirrel.Mac behavior is changed in the latest version. In older version it applied update immediately.

And yes, it seems that on windows you can only revert to a previous version in your code if a user rejects update. Maybe Update.exe has some helpful features for it, I don't know.

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
