### ISSUE TITLE
Error 404 looking for updates

### ISSUE THREAD

**Issue by t00130** [megahertz/electron-simple-updater#67]
My "updates.json":
```
{
  "win32-x64-prod": {
    "readme": "Prueba de actualizacion",
    "update": "http://localmachine/updates/win32-x64-prod-v1.6.1",
    "install": "http://localmachine/updates/win32-x64-prod-v1.6.1/AppInstaller.exe",
    "version": "1.6.1"
  }
}
```

App code in "Main.js":
```
const updater = require('electron-simple-updater');
updater.init({
  build: 'win32-x64',
  url: 'http://localmachine/updates/updates.json'
});
```
Error in log:
```
`[2019-02-25 08:08:01.485] [debug] Found version 1.6.1 at http://localmachine/updates/win32-x64-prod-v1.6.1
[2019-02-25 08:08:01.494] [info] Downloading updates from http://localmachine/updates/win32-x64-prod-v1.6.1
[2019-02-25 08:08:01.918] [warn] Error: Command failed: 4294967295
System.AggregateException: Se han producido uno o varios errores. ---> System.Net.WebException: Error en el servidor remoto: (404) No se encontr�.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- Fin del seguimiento de la pila de la excepci�n interna ---
   en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   en System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   en System.Threading.Tasks.Task`1.get_Result()
   en Squirrel.Update.Program.executeCommandLine(String[] args)
   en Squirrel.Update.Program.main(String[] args)
   en Squirrel.Update.Program.Main(String[] args)
---> (N� de excepci�n interna 0) System.Net.WebException: Error en el servidor remoto: (404) No se encontr�.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---


    at AutoUpdater.emitError (C:\Users\xxxxx\AppData\Local\app-electron\app-1.6.0\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:70:24)
    at squirrelUpdate.checkForUpdate (C:\Users\xxxx\AppData\Local\app-electron\app-1.6.0\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:46:21)
    at C:\Users\xxxxx\AppData\Local\app-electron\app-1.6.0\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:91:14
    at ChildProcess.<anonymous> (C:\Users\xxxx\AppData\Local\app-electron\app-1.6.0\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:73:14)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
`
```

**Comment by megahertz** [comment]
Seems `http://localmachine/updates/win32-x64-prod-v1.6.1/RELEASES` is missing

**Comment by t00130** [comment]
Thanks for pointing that (I didn't know RELEASES file needs to be there), for me the real problem was local IIS is not serving files without extension by default (see https://github.com/megahertz/electron-simple-updater/issues/50)
